import { NextResponse } from "next/server"
import PptxGenJS from "pptxgenjs"
import type { Presentation } from "@/lib/types"

export async function POST(req: Request) {
  try {
    const { presentation }: { presentation: Presentation } = await req.json()

    const pptx = new PptxGenJS()

    // Set presentation properties
    pptx.author = "AI Slide Generator"
    pptx.title = presentation.title
    pptx.subject = "AI Generated Presentation"

    // Title slide
    const titleSlide = pptx.addSlide()
    titleSlide.background = { color: "1a1a2e" }
    titleSlide.addText(presentation.title, {
      x: 0.5,
      y: 2.5,
      w: 9,
      h: 1.5,
      fontSize: 44,
      bold: true,
      color: "FFFFFF",
      align: "center",
    })
    titleSlide.addText("Generated by AI", {
      x: 0.5,
      y: 4,
      w: 9,
      h: 0.5,
      fontSize: 18,
      color: "8B8B8B",
      align: "center",
    })

    // Content slides
    presentation.slides.forEach((slide) => {
      const contentSlide = pptx.addSlide()
      contentSlide.background = { color: "1a1a2e" }

      // Slide title
      contentSlide.addText(slide.title, {
        x: 0.5,
        y: 0.5,
        w: 9,
        h: 0.8,
        fontSize: 32,
        bold: true,
        color: "6B7FFF",
      })

      // Content bullets
      const bulletText = slide.content.map((item) => ({
        text: item,
        options: { bullet: true, color: "FFFFFF", fontSize: 18 },
      }))

      contentSlide.addText(bulletText, {
        x: 0.5,
        y: 1.5,
        w: 9,
        h: 4,
        fontSize: 18,
        color: "FFFFFF",
      })

      // Speaker notes
      if (slide.notes) {
        contentSlide.addNotes(slide.notes)
      }
    })

    // Generate the presentation
    const pptxData = await pptx.write({ outputType: "arraybuffer" })

    return new NextResponse(pptxData as ArrayBuffer, {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "Content-Disposition": `attachment; filename="${presentation.title || "presentation"}.pptx"`,
      },
    })
  } catch (error) {
    console.error("[v0] Error generating PPT:", error)
    return NextResponse.json({ error: "Failed to generate presentation" }, { status: 500 })
  }
}
